local options = {
    autoindent = true,
    background = "dark",
    breakindent = true,
    clipboard = "unnamedplus",
    cmdheight = 2,
    colorcolumn = "100",
    completeopt = "menuone,noselect",
    conceallevel = 0,
    cursorline = true,
    errorbells = false,
    expandtab = true,
    guicursor = "",
    hlsearch = false,
    ignorecase = true,
    inccommand = "split",
    incsearch = true,
    laststatus = 2,
    list = true,
    listchars = { tab = "» ", trail = "·", nbsp = "␣" },
    mouse = "a",
    number = true,
    relativenumber = true,
    ruler = true,
    scrolloff = 8,
    sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions",
    shiftwidth = 4,
    showmode = false,
    signcolumn = "yes",
    smartcase = true,
    smartindent = true,
    softtabstop = 4,
    spell = false,
    splitbelow = false,
    splitright = true,
    syntax = "on",
    tabstop = 4,
    termguicolors = true,
    timeout = true,
    timeoutlen = 300,
    undofile = true,
    updatetime = 250,
    wrap = false,
}

for name, value in pairs(options) do
    vim.opt[name] = value
end
